#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'MX 23.6 Libretto' --class mx --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-4766xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' {
        load_video
        insmod gzio
        if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod btrfs
        set root='hd1,gptN'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd1,gptN --hint-efi=hd1,gptN --hint-baremetal=ahci1,gptN  4766xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        else
          search --no-floppy --fs-uuid --set=root 4766xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxx
        fi
        echo    'Loading Linux 6.1.0-32-amd64 ...'
        linux   /@/boot/vmlinuz-6.1.0-32-amd64 root=UUID=4766xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ro rootflags=subvol=@ video=HDMI-1:e quiet splash
        echo    'Loading initial ramdisk ...'
        initrd  /@/boot/initrd.img-6.1.0-32-amd64
}

menuentry 'Linux Mint (HDD)' --class linuxmint --class gnu-linux --class gnu --class os {
        insmod gzio
        insmod part_gpt
        insmod cryptodisk
        insmod luks
        insmod gcry_rijndael
        insmod gcry_sha256
        insmod btrfs
        cryptomount -u 31e1xxxxxxxxxxxxxxxxxxxxxxxxxxxx
        set root='cryptouuid/31e1xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint='cryptouuid/31e1xxxxxxxxxxxxxxxxxxxxxxxxxxxx'  a0a3xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        else
          search --no-floppy --fs-uuid --set=root a0a3xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        fi
        linux   /@/boot/vmlinuz root=UUID=a0a3xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ro rootflags=subvol=@  quiet splash
        initrd  /@/boot/initrd.img
}

menuentry 'Linux Mint (SSD)' --class linuxmint --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-9ca2xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' {
        load_video
        insmod gzio
        if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod ext2
        set root='hd0,gpt2'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  c3dexxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        else
          search --no-floppy --fs-uuid --set=root c3dexxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        fi
        linux   /vmlinuz root=UUID=9ca2xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ro rootflags=subvol=@ video=HDMI-1:e quiet splash
        initrd  /initrd.img
}
